name: Clear Workflow Runs

on:
  workflow_dispatch:

# 👇 아래 권한 설정을 추가해야 삭제 API를 호출할 수 있습니다.
permissions:
  actions: write
  contents: read

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
